### ISSUE TITLE
Incompatible modules on engine version 4.14.2

### ISSUE THREAD

**Issue by bobost2** [DescendentStudios/Blinken#1]
HEEELP! It's says there are incompatible modules and don't run. I need this plugin a lot

**Comment by Stormwind99** [comment]
Not enough information provided to help - please provide more details, including:

1. What version of Unreal Engine are you trying with?
2. Are you using the Epic Launcher build or a custom build?
3. Are you receiving the error from the Editor or the engine?
4. Please include relevant logs and full copy-paste of output.

**Comment by bobost2** [comment]
Last version

**Comment by Stormwind99** [comment]
Does "Last Version" mean 4.14.2, 4.13.2, or something else?  Also, please include the other requested information.

**Comment by bobost2** [comment]
4.14.2 is my version.
